<?php
echo "<!DOCTYPE html>

<html>";
echo "<title>Patrick Phalcon</title>";
echo "<div id='cssmenu'>
<link href='http://fonts.googleapis.com/css?family=Signika:400,600' rel='stylesheet' type='text/css'>
<ul>

   <li class='active'><span>";echo Phalcon\Tag::linkTo("index", "Fly"); echo "</span></a></li>

   <li><a href='#'><span>Phalcon is cool</span></a></li>

   <li><a href='#'><span>Phalcon Punch </span></a></li>

   <li><a href='#'><span>Prey</span></a></li>

   <li class='last'><span>";echo Phalcon\Tag::linkTo("signup", "Join Here"); echo "</span></li>

</ul>

</div>";
echo $this->tag->stylesheetLink("css/phalcon.css");
echo "<body align='center'>";

echo "<h1>Patrick's Phalcon Test Page Cacawwww!</h1>";


echo "<div id='boxy'>This is a paragraph.</div>\n";
echo "</body> 
</html>";



